### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by kyze8439690** [Panl/Love2048#1]
UX:
- make gesture detect on whole activity instead of viewgroup
- Animate the movement

Code:
- extends ViewGroup/FrameLayout instead of RelativeLayout to avoid extra measure

Really nice app, it successfully ruins my time. 😂

**Comment by Panl** [comment]
It‘s my honor that  you comment my project,and your suggestion is very nice,I will try to implement this function when I have time.I also want to record game progress when the user exits the game.I will be very appreciated if you can contribute to this project,thank you for your suggestions!
